### ISSUE TITLE
error: 'for' loop initial declarations are only allowed in C99 mode

### ISSUE THREAD

**Issue by zoutepopcorn** [matthijskooijman/arduino-lmic#1]
In Arduino I get the error:
error: 'for' loop initial declarations are only allowed in C99 mode

**Comment by zoutepopcorn** [comment]
With the hourly builds https://www.arduino.cc/en/Main/Software and the pinoccio plugin the raw.ino compiles.

**Comment by matthijskooijman** [comment]
This is fixed in Arduino 1.6.5 and above, as noted in the README.
