### ISSUE TITLE
Erroneous information regarding SX127x power connections

### ISSUE THREAD

**Issue by efountain** [matthijskooijman/arduino-lmic#11]
Power

"The SX127x transceivers need a supply voltage between 1.8V and 3.9V. Using a 3.3V supply is typical. The SX127x chips have various supply lines (VR_ANA, VR_DIG and VR_PA), all of which need the same supply voltage. Some modules (like the Semtech evaluation board) expose these pins separately, just connect them all together to a 3.3V source."

Note:  The VR_ANA and VR_DIG are external bypass points for regulated supplies internal to the chip at a 1.5V potential and should NOT be connected to 3.3V as this could damage the chip.  The VR_PA is the output from an internal programmable supply that is used to set the TX power level.  It also should not be connected to 3.3V because doing so could also damage the chip and prevent proper power level settings.

**Comment by matthijskooijman** [comment]
Good catch, thanks. I was a bit confused by the SX1272 evaluation board, which has multiple power input pins, and apparently made some incorrect assumptions about how these map to the SX1272 pins. Fixed in git master now!
