### ISSUE TITLE
Undefined is_runnable flag in os_runloop_once

### ISSUE THREAD

**Issue by otecfuras** [matthijskooijman/arduino-lmic#114]
After adding more debug info, unknown `is_runnable` flag appeared in `os_runloop_once`, that causes compile failure under `LMIC_DEBUG_LEVEL > 1`.

**Comment by m0lmk** [comment]
I also have this issue under LMIC_DEBUG_LEVEL > 2.

**Comment by matthijskooijman** [comment]
W00ps, that was my bad. Fixed in master now, thanks for reporting!
