### ISSUE TITLE
How to get the best RSSI

### ISSUE THREAD

**Issue by DussanR** [matthijskooijman/arduino-lmic#131]
So i wanted to know if there is a way where i can boost the power to get the best range with a single channel gateway on a raspberry pi 3. 

Thanks in advanced!

**Comment by matthijskooijman** [comment]
This repo is not for support with single-channel gateways. Also, it is meant for bug reports and feature suggestions, it's not a discussion forum to ask general questions. I suggest you try the TTN forum instead.
