### ISSUE TITLE
Debug library missing?

### ISSUE THREAD

**Issue by abreups** [matthijskooijman/arduino-lmic#176]
Documentation mentions a debug library, but I can't seem to find it (nor its functions). Any help?

**Comment by matthijskooijman** [comment]
What documentation exactly? There is debug logging support, which can be enabled by modifying `config.h` inside the library.

**Comment by abreups** [comment]
File LMiC-v1.5.pdf in section 4.8 talks about a debug library and shows functions like `void debug_init()`, `void debug_led (u1_t val)`, etc. I can't seem to find these functions anywhere.

**Comment by matthijskooijman** [comment]
Ah, that PDF is about the original upstream LMIC version, I wouldn't be surprised if it is outdated (I can't recall removing such functions in this Arduino version, but perhaps they were removed by IBM upstream and the documentation stuck around).

**Comment by abreups** [comment]
Thanks for the clarification. The document is useful, though. Only this section was "outdated".

**Comment by abreups** [comment]
For anyone interested, I found a reference to the original (I think) debug library at http://www.lancaster.ac.uk/scc/sites/lora/lorablinkkit.html
Good luck.
