### ISSUE TITLE
Channel duty limit catched up by 2 waiting messages

### ISSUE THREAD

**Issue by carabaf** [matthijskooijman/arduino-lmic#188]
I am wondering about the behavior of a device if the following case happens : 

I request a Transmission every 10 sec
The duty cycle allows transmission every 14 sec

Here is the sequence : 
00 s : TxReq
00 s : TxDone
10 s : TxReq
14 s : TxDone
20 s : TxReq
28 s : TxDone
30 s : TxReq
40 s : TxReq **--> 2 messages waiting for Tx**
...

It crashes?

**Comment by matthijskooijman** [comment]
LMIC has a buffer for 1 message only, so if you request another TX, it will overwrite the previous message.

Are you just asking a question here? Or are you actually seeing a crash that you're trying to fix?
