### ISSUE TITLE
Recived payload is just nonsense?

### ISSUE THREAD

**Issue by pekberg** [matthijskooijman/arduino-lmic#194]
Hi I'm trying to send data from GW to node and I'm sending 18 bytes of data and I'm receiving 18 bytes of data so far so good. But if you look what I'm sending and receiving things start to get somewhat messy.
Sent payload: 4c6f526157616e206973204177736f6d6521
Received payload: 3117E1643DC6CDEA2DF7A6B4A877382A1F63

I'm using the tth-otaa.ino as start :) 

And I'm dumping payload with this routine 

`for (int i = 0; i < LMIC.dataLen; i++) {
          if (LMIC.frame[LMIC.dataBeg + i] < 0x10) {
            Serial.print(F("0"));
        }
            Serial.print(LMIC.frame[LMIC.dataBeg + i], HEX);
        }`

Is there a kind soul to point me in the right direction?
Grateful for any tips!

**Comment by matthijskooijman** [comment]
Are you manually sending data from your gateway, or using TTN or a similar backend? Did you take care of encrypting the payload before sending it?

**Comment by pekberg** [comment]
I'm sending via with curl POST to GW that send it out to node..
I think this qualifies as manual...
But if I look at data in received in GW for pushing it out to node it looks correct.

It could be that I have misses encryption part

example of CURL command that I use
curl -H "Content-type:application/x-www-form-urlencoded" -X POST "https://xxx.xxxxxx.com/thingpark/lrc/rest/downlink?DevEUI=000000000F1D8693&FPort=1&Payload=0102030405060708090A&FCntDn=1"

**Comment by matthijskooijman** [comment]
> It could be that I have misses encryption part

Most likely, since gateways typically do not handle encryption. Even more, there is no encryption key in your curl command, so the gateway cannot even do encryption if it wanted to (unless you told the gateway about the encryption keys separately, but I suppose you did not).

I'll go ahead and close this issue. Feel free to post followup comments, but maybe the TTN forum might be a more suitable place (i.e. more people there) to ask :-)

**Comment by pekberg** [comment]
Thanks

**Comment by pekberg** [comment]
Finlay soled it thanks to you. I dint see the forest because of all the trees... just removed FCntDn parameter and the GW takes care of encryption..

But thanks to you I new what to look for... See below.

Hexadecimal payload. The hexadecimal payload will be encrypted by the LRC cluster if the FCntDn parameter is absent, and if the LRC has been configured with an AppSKey for the specified LoRaWAN™ port. Otherwise the payload must be encrypted by the Application Server according to the LoRaWAN™ specification, and the FCntDn parameter must be present. The Application Server encryption uses the downlink counter, which is why the FCntDn query parameter is required in this case.
