### ISSUE TITLE
Get it connected rfm95 (Sx1276)

### ISSUE THREAD

**Issue by zoutepopcorn** [matthijskooijman/arduino-lmic#2]
If you want to connect the rfm95 (Sx1276) to lib.

In the library open the file: 'lmic/config.h'

Change the following comments:
//#define CFG_eu868 1
#define CFG_us915 1
//#define CFG_sx1272_radio 1
#define CFG_sx1276_radio 1

We can't set it in the Arduino .ino file, so you have to change it in the code.

**Comment by matthijskooijman** [comment]
A note about this has been added to the README.
