### ISSUE TITLE
Join Timeout - EV_JOIN_FAILED never reached

### ISSUE THREAD

**Issue by miguel-ribeiro** [matthijskooijman/arduino-lmic#205]
In OTAA mode, when the device is not in range of a gateway, it gets "stuck" with `EV_JOINING`, and doesn't receive any other events, not even `EV_JOIN_FAILED` for the many minutes I left it running. So I have some questions, otherwise my payload seems to never get delivered and the board is stuck without a reset.

1) During this joining time, is it actively trying to join again and again with some set timeout? Or is it just waiting forever on a response that will never come because it never reached any gateway?
2) Is there a way to set a timeout to join, and try again if that timeout is reached?
3) OR Do I have to create another scheduled event of my own to do my own "timeout" and run the whole thing again?

Thanks
(testing on Arduino Pro Mini with RFM95W)

**Comment by matthijskooijman** [comment]
When joining, it will repeatedly send join requests. The rate is limited only (I think) by the duty cycle limits (which is 0.1% for join messages). It starts at SF7, and slowly increases the spreading factor up to SF12. When even at SF12 it gets no reply, it gives up with EV_JOIN_FAILED, but IIRC this takes a few hours.

You can get a bit more info about the exact state of joining by looking into LMIC's internal variables, but there's not currently any official proper API for this.

I think this should answer all three of your questions. The bottom line is probably to be patient :-)
