### ISSUE TITLE
ABP serial print garbage (arduino UNO)

### ISSUE THREAD

**Issue by v3yron** [matthijskooijman/arduino-lmic#245]
Hello,

I am having garbage printed on the serial monitor of arduino.
I am using arduino UNO and Dragino shield v1.4 and i am using ABP activation method.
The problem is that while i am receiving my messages on the gateway and it works fine but the serial monitor doesn't show anything at all it just keep showing garbage. when i switch to OTAA the garbage goes away it starts printing but gets stuck on the Join request and keep on sending the join request again and again.
I hope I have explained my problem properly. Would love an input from anyone.
Thanks in advance.

**Comment by matthijskooijman** [comment]
Did you use the right baudrate? I just noticed both examples use a different baudrate (see `Serial.begin()` in the `setup()` function), so that might be your problem?

**Comment by v3yron** [comment]
Thanks alot for a quick reply and yes that was the issue.

**Comment by matthijskooijman** [comment]
Thanks for reporting back, good to hear it's solved. I'll close this issue now :-)
