### ISSUE TITLE
OTAA communication

### ISSUE THREAD

**Issue by Ajaynithish** [matthijskooijman/arduino-lmic#259]
`#define LMIC_PRINTF_TO Serial` 
 I have uncommented  this line in config.h but still no serial data.
And while  testing OTAA  the join request and join accept keep on looping, can't able to check what is happening at node side(no serial data). And can you post any example code for testing class B operation. @matthijskooijman @robertoostenveld

**Comment by matthijskooijman** [comment]
You also need to set `LMIC_DEBUG_LEVEL`, the `LMIC_PRINTF_TO` macro only enables `printf` to be used, but does not generate any data by itself.

As for class B (beacon operation), LMIC should support that, but I have never heard anyone actually use that so far, so YMMV.
