### ISSUE TITLE
sx1278 implement

### ISSUE THREAD

**Issue by xenpac** [matthijskooijman/arduino-lmic#276]
nice code ;)

i want to use the sx1278, so the 433 mhz range.
what do i need to adjust?
thanks

**Comment by matthijskooijman** [comment]
I'm afraid LMIC does not support that, looking at https://github.com/matthijskooijman/arduino-lmic/blob/master/src/lmic/lorabase.h shows only eu868 and us915.

You could look at the https://github.com/mcci-catena/arduino-lmic version (which is still actively developed, so might be a better idea in any case), maybe they added that, or at https://github.com/LacunaSpace/basicmac which is a stack based on LMIC that might also support (haven't checked).
