### ISSUE TITLE
Gurur Meditation Error

### ISSUE THREAD

**Issue by dragosmacovei** [matthijskooijman/arduino-lmic#300]
Arduino version 1.8.13
arduino-lmic v3.3
TTGO T-Beam V1.0
Board ttgo LoRa32 OLED-v1
Upload speed: 921600
Flash freq: 40Mhz
Core debug level: None

I tried to use the lmic v3.3 library, with the `ttn-otaa` example. The code successfully uploads to the board but I got the endless loop:

On 9600 baudrate:

    Guru Meditation Error: Core  1 panic'ed (IllegalInstruction). Exception was unhandled.
    Memory dump at 0x400d19a8: ffffffff ffffffff ffffffff
    Core 1 register dump:
    PC      : 0x400d19ae  PS      : 0x00060130  A0      : 0x800d1a14  A1      : 0x3ffb1f00  
    A2      : 0x3ffc0170  A3      : 0x000000ff  A4      : 0x3f4010fc  A5      : 0x00000403  
    A6      : 0x00ff0000  A7      : 0xff000000  A8      : 0x800d198f  A9      : 0x3ffb1ee0  
    A10     : 0x000000ff  A11     : 0x00000000  A12     : 0x00000002  A13     : 0x0000ff00  
    A14     : 0x00ff0000  A15     : 0xff000000  SAR     : 0x0000001a  EXCCAUSE: 0x00000000  
    EXCVADDR: 0x00000000  LBEG    : 0x400014fd  LEND    : 0x4000150d  LCOUNT  : 0xffffffff  

    Backtrace: 0x400d19ae:0x3ffb1f00 0x400d1a11:0x3ffb1f20 0x400d3e1b:0x3ffb1f40 0x400d3e32:0x3ffb1f60 0x400d10cd:0x3ffb1f80 0x400d59ab:0x3ffb1fb0 0x40088215:0x3ffb1fd0

On 115200 baudrate:

    rst:0xc (SW_CPU_RESET),boot:0x13 (SPI_FAST_FLASH_BOOT)
    configsip: 0, SPIWP:0xee
    clk_drv:0x00,q_drv:0x00,d_drv:0x00,cs0_drv:0x00,hd_drv:0x00,wp_drv:0x00
    mode:DIO, clock div:2
    load:0x3fff0018,len:4
    load:0x3fff001c,len:1044
    load:0x40078000,len:8896
    load:0x40080400,len:5828
    entry 0x400806ac

Decoding the 9600 baudrate message with exception decoder:

```
PC: 0x400d19ae: **Arduino_LMIC::hal_init_with_pinmap(Arduino_LMIC::HalPinmap_t const*)** at C:\Users\USR\OneDrive\Documents\Arduino\libraries\arduino-lmic-3.3.0\src\hal\ **hal.cpp** line **53** 
EXCVADDR: 0x00000000 *Decoding stack results* 0x400d19ae: 

**Arduino_LMIC::hal_init_with_pinmap(Arduino_LMIC::HalPinmap_t const*)** at C:\Users\USR\OneDrive\Documents\Arduino\libraries\arduino-lmic-3.3.0\src\hal\ **hal.cpp** line **53** 
0x400d1a11: **hal_init_ex(void const*)** at C:\Users\USR\OneDrive\Documents\Arduino\libraries\arduino-lmic-3.3.0\src\hal\ **hal.cpp** line **425** 
0x400d3e1b: **os_init_ex** at C:\Users\USR\OneDrive\Documents\Arduino\libraries\arduino-lmic-3.3.0\src\lmic\ **oslmic.c** line **43**
0x400d3e32: **os_init** at C:\Users\USR\OneDrive\Documents\Arduino\libraries\arduino-lmic-3.3.0\src\lmic\ **oslmic.c** line **51**
0x400d10cd: **setup()** at C:\Users\USR\OneDrive\Documents\Arduino\Current_working_at/ **Current_working_at.ino** line **181**
0x400d59ab: **loopTask(void*)** at C:\Users\USR\OneDrive\Documents\ArduinoData\packages\esp32\hardware\esp32\1.0.4\cores\esp32\ **main.cpp** line **14**
0x40088215: **vPortTaskWrapper** at /home/runner/work/esp32-arduino-lib-builder/esp32-arduino-lib-builder/esp-idf/components/freertos/ **port.c** line **143**
```

**Comment by matthijskooijman** [comment]
Thanks for your submission, but you seem to be using a different version of the LMIC library (I see version 3.3.0, there is no such version in this repo). I'm not sure where your version comes from, but I'm afraid you'll have to look for support elsewhere. I'm closing this.
