### ISSUE TITLE
Will this Library works with 433 Mhz hardware ?

### ISSUE THREAD

**Issue by Faizan2253** [matthijskooijman/arduino-lmic#304]
I have SX1278 LoRa module and RAK831 LoRa Wan Gateway. (433 Mhz). Will this library work with 433Mhz hardware? I can't see 433 Mhz frequency to select in config file from where you can select your region.

**Comment by matthijskooijman** [comment]
I do not think the frequency plan is supported by the current code and development on this version of LMIC has stopped, so it won't be added either. Maybe you could check out the MCCI version of LMIC (see README), maybe they added 433Mhz support already?
