### ISSUE TITLE
FAILURE after uploading helium-otaa to esp32 channel 1 lora board

### ISSUE THREAD

**Issue by clementpeleman** [matthijskooijman/arduino-lmic#305]
Hi, I am getting the following error in the serial monitor:

FAILURE
C:\Arduino\libraries\MCCI_LoRaWAN_LMIC_library\src\lmic\radio.c:1164

I kind of tricked the code into thinking it is the ttgo_lora32 because I can not firugre out how to write my own pinmap. I think these boards use the same pins for connecting the RFM95 to the esp32.

Any help with the error or on a pinmap would be appreciated!
Clement

**Comment by matthijskooijman** [comment]
Looks like you're using the MCCI version of this library, which lives at https://github.com/mcci-catena/arduino-lmic, so I suggest you ask there instead.
