### ISSUE TITLE
What are opmodes? Are they listed somewhere?

### ISSUE THREAD

**Issue by tipo1000A** [matthijskooijman/arduino-lmic#309]
As the title says arduino-lmic prints opmodes like:
opmode=0x4
opmode=0x808
opmode=0x900
opmode=0x908
. . ,
What they mean?

Thanks,
Tipo

**Comment by matthijskooijman** [comment]
It's a bitmask of these: https://github.com/matthijskooijman/arduino-lmic/blob/e6061a5171f4e00e84259bb5df41cb023b3d3667/src/lmic/lmic.h#L114-L128
