### ISSUE TITLE
Sending data in uint32 instead of uint8

### ISSUE THREAD

**Issue by magicBanana3** [matthijskooijman/arduino-lmic#310]
Hello,
I'm new in the world of creating of LoRaWAN-Nodes. 
I'm able to send data via LoRaWAN with this library, but the format of 8 bits is not enough for my use case. 
Does anyone of you know how to send data in the 32 bit format?

I'm very thankful for your comments and your help.

Best wishes

**Comment by matthijskooijman** [comment]
This library is no longer actively supported, so I'm closing this issue.

Like any radio or communication library, LMIC just sends a sequence of bytes, and it is up to you to encode your data into such a byte sequence. There should be tons of examples on the internet on how to do this, search terms might be "packetization", "packing into bytes", "encoding into byte string", that kind of thing.

Good luck!
