### ISSUE TITLE
Pinmap T-BEam compiler Error

### ISSUE THREAD

**Issue by Lordcybertracker** [matthijskooijman/arduino-lmic#311]
Ich have the T-Beam Board.

In Arduino IDE come:
C:\Users\laval\Documents\Arduino\libraries\MCCI_LoRaWAN_LMIC_library-4.0.0\src\hal\getpinmap_thisboard.cpp: In function 'const Arduino_LMIC::HalPinmap_t* Arduino_LMIC::GetPinmap_ThisBoard()':
C:\Users\laval\Documents\Arduino\libraries\MCCI_LoRaWAN_LMIC_library-4.0.0\src\hal\getpinmap_thisboard.cpp:69:72: note: #pragma message: Board not supported -- use an explicit pinmap
         #pragma message("Board not supported -- use an explicit pinmap")
                                                                        ^
c:/users/laval/appdata/local/arduino15/packages/esp32/tools/xtensa-esp32-elf-gcc/gcc8_4_0-esp-2021r2/bin/../lib/gcc/xtensa-esp32-elf/8.4.0/../../../../xtensa-esp32-elf/bin/ld.exe: C:\Users\laval\AppData\Local\Arduino15\packages\esp32\hardware\esp32\2.0.2/tools/sdk/esp32/lib\libpp.a(hal_mac.o): in function `hal_init':
(.text.hal_init+0xb4): multiple definition of `hal_init'; libraries\MCCI_LoRaWAN_LMIC_library-4.0.0\hal\hal.cpp.o:C:\Users\laval\Documents\Arduino\libraries\MCCI_LoRaWAN_LMIC_library-4.0.0\src\hal/hal.cpp:416: first defined here
collect2.exe: error: ld returned 1 exit status
Mehrere Bibliotheken wurden für "SSD1306Wire.h" gefunden
 Benutzt: C:\Users\laval\Documents\Arduino\libraries\ESP8266_and_ESP32_OLED_driver_for_SSD1306_displays
 Nicht benutzt: C:\Users\laval\Documents\Arduino\libraries\esp8266-oled-ssd1306-master
exit status 1
Fehler beim Kompilieren für das Board T-Beam.

**Comment by matthijskooijman** [comment]
This library is no longer developed and not supported anymore. I would recommend you switch to the MCCI version of LMIC, but it actually seems you are already using that version, so you should probably ask for support over there.

(Looking at the actual message, it seems to me that MCCI LMIC simply has no builtin pin mapping configuration for your board, so you just need to provide your own pin map to tell the library which pins are connected where).

**Comment by chegewara** [comment]
It is also conflict `hal_init` with the same function in arduino-esp32.
I would suggest to change it in local library copy.
