### ISSUE TITLE
Problem PicoD4

### ISSUE THREAD

**Issue by Lordcybertracker** [matthijskooijman/arduino-lmic#312]
Hello,
I use an ESP32 Pico D4 and an RFM95.
The last time I used it everything worked.
But now I get the following error in the Arduino IDE as well as PlatformIO:

pin map is:
#define PIN_LMIC_NSS 5
#define PIN_LMIC_RST 14
#define PIN_LMIC_DIO0 25
#define PIN_LMIC_DIO1 37
#define PIN_LMIC_DIO2 38

// Pin mapping
const lmic_pinmap lmic_pins = {
    .nss = PIN_LMIC_NSS,
    .rxtx = LMIC_UNUSED_PIN,
    .rst = PIN_LMIC_RST,
    .dio = {PIN_LMIC_DIO0, PIN_LMIC_DIO1, PIN_LMIC_DIO2},
};

Mistake:
Compiling .pio\build\pico32\src\main.cpp.o
Linking .pio\build\pico32\firmware.elf
c:/users/laval/.platformio/packages/toolchain-xtensa-esp32/bin/../lib/gcc/xtensa-esp32-elf/8.4.0/../../../../xtensa -esp32-elf/bin/ld.exe: C:\Users\laval\.platformio\packages\framework-arduinoespressif32\tools\sdk\esp32\lib\libpp.a(hal_mac.o): in function `hal_init': (.text.hal_init+0xc8): multiple definition of `hal_init'; .pio\build\pico32\lib051\libMCCI LoRaWAN LMIC library.a(hal.cpp.o):C:\Users\laval\Documents\PlatformIO\Projects\HSN-TTN_Esp32 V1.1\HSN-TTN_Esp32 V1.1/ .pio/libdeps/pico32/MCCI LoRaWAN LMIC library/src/hal/hal.cpp:416: first defined here
collect2.exe: error: ld returned 1 exit status
*** [.pio\build\pico32\firmware.elf] Error 1

Please how can I fix this because it can continue to work.
Thanks

**Comment by matthijskooijman** [comment]
Hi, this library is not longer developed. It seems you are already using the MCCI fork of this library, so I recommend you seek support in their repository, not here. Thanks!
