### ISSUE TITLE
Request to Update Code for Join Request with RSSI Constant

### ISSUE THREAD

**Issue by tarq2000** [matthijskooijman/arduino-lmic#314]
Hello 

I’ve been using the project, and I have a suggestion that could improve its functionality.

Would it be possible to modify the code to allow sending a join request with a fixed RSSI value, for example, RSSI = -80? 

If you prefer, I can help test the changes once implemented or provide more details about the use case.

Thank you for considering this request.

**Comment by matthijskooijman** [comment]
Hi! I'm no longer maintaining this project, see the README for details and suggestions of other forks to look at.
