### ISSUE TITLE
Arduino/Genduino 101

### ISSUE THREAD

**Issue by rodriguise** [matthijskooijman/arduino-lmic#36]
working with the sx1276 based rfm95 chip I have no issue using the UNO but when working with the Arudino 101 I get the following error:

```
Starting
FAILURE 
/Users/rob/Documents/Arduino/libraries/arduino-lmic/src/lmic/radio.c:708
VAL: 0x09
EXP: 0x12
```

It is mentioned in the readme that the 101 has been tested. Were there any changes necessary to make this work?

**Comment by rodriguise** [comment]
I found this PR to be relevant:
https://github.com/matthijskooijman/arduino-lmic/pull/27

I dropped the spi to 1Mhz and things seem to be working well now.

```
//hal.cpp
static const SPISettings settings(10E6, MSBFIRST, SPI_MODE0);
```

```
static const SPISettings settings(10E5, MSBFIRST, SPI_MODE0);
```

**Comment by matthijskooijman** [comment]
Thanks for reporting back. I'll close this issue in favor of that PR.
