### ISSUE TITLE
Support SX1231 or RFM69HCW

### ISSUE THREAD

**Issue by sabas1080** [matthijskooijman/arduino-lmic#56]
Hi

The library support chip SX1231 or RFM69HCW?

Thanks

**Comment by matthijskooijman** [comment]
Nope, only the SX127x chips are supported by this library. Looking at the chip you mention, that does not even seem to be a LoRa chip, so it does not really make sense to use it with this library.

Did you look at http://www.airspayce.com/mikem/arduino/RadioHead/ which does seem to support that chip?

I'm closing this issue, feel free to add comments if you have followup questions!
