### ISSUE TITLE
How can i modify raw.ino ??

### ISSUE THREAD

**Issue by pluss2** [matthijskooijman/arduino-lmic#63]
I successfully porting raw.ino in Arudino UNO.

Is original raw.ino transmit code, right ?

Then, how do i modify raw.ino to receiving node ?

**Comment by matthijskooijman** [comment]
The code already receives when not transmitting, see https://github.com/matthijskooijman/arduino-lmic/blob/master/examples/raw/raw.ino#L10-L12

However, this example isn't really the best way to use the library, for node-to-node communication I believe better libraries are available, such as radiohead.

**Comment by pluss2** [comment]
The reason why i discussed with this issue is both node doesn't receive any data.

Ok, i will find the other way with radiohead. 
Thank you so much,

**Comment by nafitriaulia** [comment]
Do you success to communicate node peer to peer?
